export const GET_COUNTRY = 'GET_COUNTRY';
export const CLEAR_COUNTRY = 'CLEAR_COUNTRY';
export const SET_LOADING = 'SET_LOADING';
export const GET_COUNTRY_ERROR = 'GET_COUNTRY_ERROR';
export const SEARCH_COUNTRY = 'SEARCH_COUNTRY';
export const ADD_LIST = 'ADD_LIST';